### PR TITLE
Add official logo

### PR DESCRIPTION
**Pull request by azigler**
Adding the new logo from JuliAnn Tulberg via @BenLloydPearson.

### CODE REVIEW

**Comment by azigler** [comment]
Hi @stylianosrigas! Just wanted to follow up on this PR. This adds a logo to the project's README that was designed by JuliAnn, since we made a handful of logos with a unique style for our various open source repos (rotator being one of them). Let me know if you have any questions about it.

**Review by stylianosrigas — APPROVED** [review]
That is awesome thanks, approved :)

**Comment by stafot** [comment]
@azigler since `rotatorctl` is child project of this could we use the same logo there?

**Comment by azigler** [comment]
> @azigler since `rotatorctl` is child project of this could we use the same logo there?

Yep, let me get a PR over there for you. We'll use the same logo.

**Comment by azigler** [comment]
@stafot Okay, submitted that PR! https://github.com/mattermost/rotatorctl/pull/14

**Pull request merged**
